config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: "users#index"

# Show User
get "/users", to: "users#show", as: "users"

#create new users
get "/users/new", to: "users#new", as: "new_users"
post "/users", to: "users#create"

# Show recipients
get "/recipients", to: "recipients#show", as: "recipients"

# Create New recipients
get "/recipients/new", to: "recipients#new", as: "new_recipients"
post "/recipients", to: "recipients#create"

#Show Gifts
get "/gifts", to: "gifts#show", as: "gifts"

#show order
get "/orders", to: "orders#show", as: "orders"

post "/order", to: "order#create"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gift.rb
class Gift < ApplicationRecord
    has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :recipient
  belongs_to :gift
end

app/models/recipient.rb
class Recipient < ApplicationRecord
    has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController

    def index

    @gifts = Gift.all.order(:category)

    end

    def show
        
    @gifts = Gift.all
    
    end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
    def show

        @recipient = Recipient.all
    
    end

    def new
        @recipient = Recipient.new
    end

    def create
        recipient = Recipient.create_recipient(params[:user][:first_name], params[:user][:last_name], params[:user][:address])
    end
end
    

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        if user_signed_in?
            redirect_to users_path 
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gifts/show.html.erb
<h1>Gift Options</h1>

<% @gifts.each do |gift|%>
    
    
    <p><h4><%=gift.category%></h4></p>
  
    <p><%=image_tag "#{gift.image_path}", class: "img-thumbnail box", width: 200%>
     <div class="form-check">
  <input class="form-check-input position-static" type="checkbox" id="blankCheckbox" value="option1" aria-label="...">
</div>
      
    </p>
    <p><h5><%=gift.name %></h5></p>
    
    <p>PRICE: $<%=gift.price%></p>
    
<%end%>
<p><%=link_to 'Redeem Your Gift', new_recipients_path, class:"btn btn-warning" %></p>
<p><%=link_to 'Back', users_path, class:"btn btn-primary" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Love You/rself</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render "shared/topnav"%>
 
    <div class="container">
    
    <% if notice %>
      <p class="alert alert-success" role="alert"><%= notice %></p>
    <%end%>
    <%if alert %>
      <p class="alert alert-danger" role="alert"><%= alert %></p>
    <%end%>
      <%= yield %>
    </div>
  
    <%= render "shared/footer"%>
  </body>
</html>

app/views/recipients/new.html.erb
<h1>Who would you like your gift to go to???</h1>

<form>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputFirstname">First Name</label>
      <input type="text" class="form-control" id="inputFirstname">
    </div>
    <div class="form-group col-md-6">
      <label for="inputLastname">Last Name</label>
      <input type="text" class="form-control" id="inputLastname">
    </div>
  </div>
  <div class="form-group">
    <label for="inputAddress">Address</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
  </div>
  <div class="form-group">
    <label for="inputAddress2">Address 2</label>
    <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputCity">City</label>
      <input type="text" class="form-control" id="inputCity">
    </div>
    <div class="form-group col-md-4">
      <label for="inputState">State</label>
      <select id="inputState" class="form-control">
        <option selected>Choose...</option>
            <option value="1">ACT</option>
            <option value="2">NSW</option>
            <option value="3">NT</option>
            <option value="4">QLD</option>
            <option value="5">VIC</option>
            <option value="6">TAS</option>
            <option value="7">WA</option>
      </select>
    </div>
    <div class="form-group col-md-2">
      <label for="inputPostcode">Postcode</label>
      <input type="text" class="form-control" id="inputPostcode">
    </div>
  </div>

  
  <a href="/recipients" type="submit" class="btn btn-primary" >Submit</a>
  
</form>

app/views/recipients/show.html.erb
<div class="text-center">

<%=image_tag "cupid.jpg",  width: 400 %>



<h1>Your order is confirmed and it's on its way!!!!</h1>

<p><%=link_to 'Return to Homepage', users_path, class:"btn btn-danger" %></p>

</div>

app/views/shared/_footer.html.erb
<footer class="footer row align-items-end">
<div class="col text-right">
 
 <div>
</footer>

app/views/shared/_topnav.html.erb
<header class="top-nav row align-items-end">
<div class="logo">
<h1><a href="/">Love You/rself</a></h1>
</div>
<div class="col text-right">
 <% if user_signed_in? %>
   <div id="signout"><%= link_to 'Sign out', destroy_user_session_path, method: "delete",class:"top-nav-link"%></div>
   <div ><%= current_user.email %></div>
    <% else %>
   <p><%= link_to 'Sign In', new_user_session_path, class:"top-nav-link"%>
   |
   <%= link_to 'Sign Up', new_user_registration_path, class:"top-nav-link"%>
   </p>
 <% end %>
 <div>
</header>

app/views/users/index.html.erb
<h1>Love You/rself</h1>
<h2>
<%= link_to 'Sign Up', new_user_registration_path%>
/
<%= link_to 'Sign In', new_user_session_path%>
</h2>
<img src="/assets/Thank-you-for-your-Love.jpg" />

app/views/users/new.html.erb
<h1>Add your details</h1>

<form>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputFirstname">First Name</label>
      <input type="text" class="form-control" id="inputFirstname">
    </div>
    <div class="form-group col-md-6">
      <label for="inputLastname">Last Name</label>
      <input type="text" class="form-control" id="inputLastname">
    </div>
  </div>
  <div class="form-group">
    <label for="inputAddress">Address</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
  </div>
  <div class="form-group">
    <label for="inputAddress2">Address 2</label>
    <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputCity">City</label>
      <input type="text" class="form-control" id="inputCity">
    </div>
    <div class="form-group col-md-4">
      <label for="inputState">State</label>
      <select id="inputState" class="form-control">
        <option selected>Choose...</option>
            <option value="1">ACT</option>
            <option value="2">NSW</option>
            <option value="3">NT</option>
            <option value="4">QLD</option>
            <option value="5">VIC</option>
            <option value="6">TAS</option>
            <option value="7">WA</option>
      </select>
    </div>
    <div class="form-group col-md-2">
      <label for="inputPostcode">Postcode</label>
      <input type="text" class="form-control" id="inputPostcode">
    </div>
  </div>
  <button type="submit" class="btn btn-info">Sign in</button>
</form>

app/views/users/show.html.erb
<% if user_signed_in? %>
<h1>Hello there...</h1>

<div class="row container">
  <div class="col-sm-6 align-self-center">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Subscribe Today</h5>
        <p class="card-text">Subscribe to the greatest thing to happen to lazy people since Bootstrap! Save towards buying that special gift for that special someone... or TREAT YO SELF!</p>
        <a href="https://demo.tutorialzine.com/2016/11/simple-credit-card-validation-form/" class="btn btn-success">Subscribe!</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6 align-self-center">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Redeem Your Gift</h5>
        <p class="card-text">Have you reached your gift cap? Awesome! You can now access our gift collection. Click here to redeem your gift for your chosen special one! Or 'Number One'!</p>
        <a href="/gifts" class="btn btn-warning">Redeem!</a>
      </div>
    </div>
  </div>
</div>
<% end %>